print("Hello World")
print("Next Line")
print("Third Line")
x=16
print(x)
print(x*x)
print("x=",x)
x=21
print(x)
#min_day=int(input("How many minutes a day do you exercise? "))
min_day=100
min_week=min_day*7
print("You exercised",min_week,"minutes this week!")
noun=input("Please enter a noun: ")
print("I'll look back on this and smile because it was",noun,"and I decided to live it!")
noun1=input("Please enter a noun: ")
noun2=input("Please enter another noun: ")
adj1=input("Please enter an adjective: ")
adj2=input("Please enter another adjective: ")
adj3=input("Please enter one more adjective: ")
number1=input("Please enter a numerical value: ")
number2=input("Please enter another numerical value: ")
object1=input("Please enter an object: ")
action1=input("Please enter an action: ")
action2=input("Please enter another action: ")
option=input("Please enter one of the following: always, sometimes, never: ")
print("Here's to the",noun1,"who")
print("try their",adj1,"to")
print("be",adj2,"enough for everyone;")
print("who spend,number1, hours")
print("reading random")
print("quotes to find the")
print(noun2,"one; who",action1)
print("to the same",object1)
print(number2,"times")
print("because the lyrics")
print("mean a lot;")
print("who deserve")
print("so much more")
print("than they get")
print("and are willing")
print("to",action2,"for it")
print("and whose wish")
print("upon a shooting star")
print("was",adj3,"on someone")
print("that will",option,"care.")
