print("LLLL         BBBBBBB      SSSSSSSSS")
print(" LL          BB     B     SS      S")
print(" LL          BB      B    SS       ")
print(" LL          BB     B     SS       ")
print(" LL          BBBBBBB      SSSSSSSSS")
print(" LL          BB     B            SS")
print(" LL          BB      B           SS")
print(" LL      L   BB     B     S      SS")
print("LLLLLLLLLL   BBBBBBB      SSSSSSSSS")