print("BBBBBBBB        DDDDDDDDDDDD           LLLL                     CCCCCCCC")
print(" BB    BB        DD        DD           LL                     CCCCC  CC")
print(" BB     BB       DD         DD          LL                    CCCCC     ")
print(" BB      BB      DD          DD         LL                   CCCCC      ")
print(" BB       BB     DD           DD        LL                  CCCCC       ")
print(" BB      BB      DD            DD       LL                 CCCC         ")
print(" BB     BB       DD             DD      LL                CCC           ")
print(" BBBBBBBB        DD              DD     LL               CC             ")
print(" BB     BB       DD             DD      LL                CCC           ")
print(" BB      BB      DD            DD       LL                 CCCC         ")
print(" BB       BB     DD           DD        LL                  CCCCC       ")
print(" BB      BB      DD          DD         LL                   CCCCC      ")
print(" BB     BB       DD         DD          LL                    CCCCC     ")
print(" BB    BB        DD        DD           LL              LL     CCCCC  CC")
print("BBBBBBBB        DDDDDDDDDDDD           LLLLLLLLLLLLLLLLLLL      CCCCCCCC")